Repository StackExchange/Stacks, pull requests merged in 2018-07, with the labels that each got.

#57 Make button sizes and loading work
  docs/assets/css/stacks-documentation.css
  docs/assets/css/stacks-documentation.min.css
  lib/css/stacks.css
  lib/css/stacks.min.css
  lib/src/components/_stacks-buttons.less
Labels: bug

#76 Update page-nomenu template to match page template
  docs/_layouts/page-nomenu.html
Labels: docs

#70 Add progress bars into Stacks
  docs/_data/nav.yml
  docs/assets/css/stacks-documentation.css
  docs/assets/css/stacks-documentation.min.css
  docs/components/modals.html
  docs/components/progress-bars.html
  lib/css/stacks.css
  lib/css/stacks.min.css
  lib/src/components/_stacks-progress-bars.less
  lib/src/exports/_stacks-constants-colors.less
  lib/src/stacks-static.less
Labels: feature, status-planned
