Repository StackExchange/Stacks, pull requests merged in 2018-09, with the labels that each got.

#131 Add s-tag__danger class for when a tag is incorrect.
  docs/_data/product/tags.yaml
  docs/assets/css/stacks-documentation.css
  docs/assets/css/stacks-documentation.min.css
  docs/product/components/tags.html
  lib/css/stacks.css
  lib/css/stacks.min.css
  lib/src/base/_stacks-configuration-dynamic.less
  lib/src/components/_stacks-tags.less
Labels: feature

#152 Fixing one of flex-wrap values
  docs/_data/product/grid.yaml
  docs/assets/css/stacks-documentation.css
  docs/assets/css/stacks-documentation.min.css
  lib/css/stacks.css
  lib/css/stacks.min.css
  lib/src/atomic/_stacks-flex.less
Labels: bug

#147 Email footers
  docs/_data/nav.yml
  docs/assets/css/stacks-documentation.min.css
  docs/email/components/footers.html
  lib/css/stacks.min.css
Labels: email, enhancement
