Repository StackExchange/Stacks, pull requests merged in 2020-07, with the labels that each got.

#507 Prose component
  docs/.eleventy.js
  docs/_data/site-navigation.json
  docs/_includes/markdown-post.md
  docs/_includes/markdown-prose.md
  docs/_includes/markdown-readme.md
  docs/_includes/markdown-sandbox.md
  docs/assets/js/spoilers.js
  docs/product/components/prose.html
  lib/css/components/_stacks-prose.less
  lib/css/stacks-static.less
  package-lock.json
  package.json
Labels: feature

#511 Add official browserslist to package.json
  package.json
Labels: enhancement

#513 Add _important to forced white, add forced black
  lib/css/atomic/_stacks-colors.less
Labels: discussion

#514 Update Brand logos page
  docs/assets/img/logos/audience/soa-logo-compact.png
  docs/assets/img/logos/audience/soa-logo-compact.svg
  docs/assets/img/logos/audience/soa-logo.png
  docs/assets/img/logos/audience/soa-logo.svg
  docs/assets/img/logos/se/se-icon.png
  docs/assets/img/logos/se/se-icon.svg
  docs/assets/img/logos/se/se-logo-med.png
  docs/assets/img/logos/se/se-logo.eps
  docs/assets/img/logos/se/se-logo.png
  docs/assets/img/logos/se/se-logo.svg
  docs/assets/img/logos/sf/sf-icon.png
  docs/assets/img/logos/sf/sf-icon.svg
  docs/assets/img/logos/sf/sf-logo-med.png
  docs/assets/img/logos/sf/sf-logo.eps
  docs/assets/img/logos/sf/sf-logo.png
  docs/assets/img/logos/sf/sf-logo.svg
  docs/assets/img/logos/so/logo-br.pdf
  docs/assets/img/logos/so/logo-br.png
  docs/assets/img/logos/so/logo-br.svg
  docs/assets/img/logos/so/logo-community.svg
  docs/assets/img/logos/so/logo-community__breakdown.svg
  docs/assets/img/logos/so/logo-es.pdf
  docs/assets/img/logos/so/logo-es.png
  docs/assets/img/logos/so/logo-es.svg
  docs/assets/img/logos/so/logo-jp.pdf
  docs/assets/img/logos/so/logo-jp.png
  docs/assets/img/logos/so/logo-jp.svg
  docs/assets/img/logos/so/logo-meta.png
  docs/assets/img/logos/so/logo-meta.svg
  docs/assets/img/logos/so/logo-meta__breakdown.svg
  docs/assets/img/logos/so/logo-print.svg
  docs/assets/img/logos/so/logo-ru.pdf
  docs/assets/img/logos/so/logo-ru.png
  docs/assets/img/logos/so/logo-ru.svg
  docs/assets/img/logos/so/logo-screen.svg
  docs/assets/img/logos/so/logo-stackoverflow.png
  docs/assets/img/logos/so/logo-stackoverflow.svg
  docs/assets/img/logos/so/logo-stackoverflow__breakdown.svg
  docs/assets/img/logos/so/logo-stacks@2x.png
  docs/assets/img/logos/su/su-icon.png
  docs/assets/img/logos/su/su-icon.svg
  docs/assets/img/logos/su/su-logo-med.png
  docs/assets/img/logos/su/su-logo.eps
  docs/assets/img/logos/su/su-logo.png
  docs/assets/img/logos/su/su-logo.svg
  docs/assets/img/logos/talent/talent-logo-compact.png
  docs/assets/img/logos/talent/talent-logo-compact.svg
  docs/assets/img/logos/talent/talent-logo.png
  docs/assets/img/logos/talent/talent-logo.svg
  docs/assets/img/logos/teams/teams-logo-compact.png
  docs/assets/img/logos/teams/teams-logo-compact.svg
  docs/assets/img/logos/teams/teams-logo.png
  docs/assets/img/logos/teams/teams-logo.svg
  docs/brand/logo.html
  package-lock.json
Labels: brand

#518 Bump dependencies
  dist/js/stacks.js
  dist/js/stacks.min.js
  docs/_data/iconsEleventy.json
  package-lock.json
  package.json
Labels: dependencies
