Repository StackExchange/Stacks, pull requests merged in 2020-08, with the labels that each got.

#525 Tweak s-prose styles
  lib/css/components/_stacks-prose.less
Labels: bug

#524 Add a display delay to the s-popover__tooltip component
  dist/js/stacks.js
  dist/js/stacks.min.js
  lib/ts/controllers/s-tooltip.ts
Labels: enhancement

#526 Add small variation to s-prose
  docs/product/components/prose.html
  lib/css/components/_stacks-prose.less
  lib/css/exports/_stacks-constants-type.less
Labels: enhancement

#530 Add company email signatures
  docs/_data/site-navigation.json
  docs/email/components/signatures.html
Labels: brand

#531 List nesting refinements
  docs/_includes/markdown-sandbox.md
  lib/css/components/_stacks-prose.less
Labels: bug

#532 Spoiler behavior
  docs/assets/js/spoilers.js
  lib/css/components/_stacks-prose.less
Labels: bug

#533 Tighten up the line height of code blocks
  lib/css/components/_stacks-code-blocks.less
  lib/css/components/_stacks-prose.less
Labels: enhancement

#534 Prose spacing refinements
  lib/css/components/_stacks-prose.less
  lib/css/exports/_stacks-constants-type.less
Labels: enhancement

#535 s-code-block style tweaks
  docs/assets/less/stacks-documentation.less
  lib/css/components/_stacks-code-blocks.less
  lib/css/components/_stacks-prose.less
Labels: bug
