Repository StackExchange/Stacks, pull requests merged in 2020-03, with the labels that each got.

#452 Add Integrations email to email announcement gallery
  docs/email/templates/examples/integrations.html
  docs/email/templates/examples/integrations.png
  docs/email/templates/major-announcements.html
Labels: email

#427 Update Modal typography
  lib/css/components/_stacks-modals.less
Labels: discussion, exploration

#449 Component / Link previews
  docs/_data/link-previews.json
  docs/_data/site-navigation.json
  docs/product/components/link-previews.html
  lib/css/components/_stacks-link-previews.less
  lib/css/stacks-dynamic.less
Labels: feature

#465 Update Popper 1.x to version 2.x
  Gruntfile.js
  dist/js/stacks.js
  dist/js/stacks.min.js
  lib/css/components/_stacks-popovers.less
  lib/ts/controllers/s-popover.ts
  package-lock.json
  package.json
Labels: dependencies, product

#469 Add dispatching element to the popover and modal's event details
  dist/js/stacks.js
  dist/js/stacks.min.js
  docs/product/components/modals.html
  docs/product/components/popovers.html
  lib/ts/controllers/s-modal.ts
  lib/ts/controllers/s-popover.ts
  lib/ts/controllers/s-tooltip.ts
Labels: docs, enhancement
