Repository StackExchange/Stacks, pull requests merged in 2021-02, with the labels that each got.

#588 Ensure dispatcher is set on shown/hidden events
  lib/ts/controllers/s-popover.ts
Labels: bug

#590 Circular progress bars
  docs/product/components/progress-bars.html
  lib/css/components/_stacks-progress-bars.less
Labels: enhancement

#597 Bump Popper to 2.8.4
  dist/js/stacks.js
  dist/js/stacks.min.js
  package-lock.json
  package.json
Labels: dependencies
