Repository StackExchange/Stacks, pull requests merged in 2021-01, with the labels that each got.

#574 Simplify button disabled states
  lib/css/base/_stacks-configuration-dynamic.less
  lib/css/components/_stacks-buttons.less
Labels: enhancement

#576 Call out when exactly to use `aria-pressed`
  docs/product/components/buttons.html
Labels: docs

#569 Additional variables
  lib/css/atomic/_stacks-typography.less
  lib/css/base/_stacks-body.less
  lib/css/base/_stacks-configuration-dynamic.less
  lib/css/components/_stacks-prose.less
  lib/css/exports/_stacks-constants-colors.less
  lib/css/exports/_stacks-constants-type.less
Labels: enhancement

#577 s-user-card improvements
  docs/product/components/user-cards.html
  lib/css/components/_stacks-user-cards.less
Labels: enhancement

#572 s-navigation-tablist controller
  dist/js/stacks.js
  dist/js/stacks.min.js
  docs/product/components/navigation.html
  lib/ts/controllers/s-navigation-tablist.ts
Labels: javascript
