Repository StackExchange/Stacks, pull requests merged in 2021-06, with the labels that each got.

#683 Deprecate a few flex atomic classes
  docs/.eleventy.js
  docs/_data/grids.json
  docs/_includes/layouts/home.html
  docs/_includes/layouts/page.html
  docs/_includes/navigation.html
  docs/email/guidelines/getting-started.html
  docs/product/base/grid.html
  docs/product/components/inputs.html
  docs/product/components/progress-bars.html
  docs/product/resources/icons.html
  docs/product/resources/spots.html
  lib/css/atomic/_stacks-flex.less
  lib/css/atomic/_stacks-grid.less
Labels: deprecation

#689 Transition `grid` to `d-flex`
  docs/_data/flex.json
  docs/_data/site-navigation.json
  docs/_includes/navigation.html
  docs/assets/less/stacks-documentation.less
  docs/product/base/flex.html
  docs/product/base/grid.html
  docs/product/components/tables.html
  lib/css/atomic/_stacks-flex.less
  lib/css/atomic/_stacks-grid.less
  lib/css/stacks-static.less
  netlify.toml
Labels: deprecation

#691 Various documentation improvements
  docs/.eleventy.js
  docs/_includes/header.html
  docs/_includes/layouts/page-nomenu.html
  docs/_includes/layouts/page.html
  docs/_includes/navigation.html
  docs/assets/js/search.js
  docs/assets/less/stacks-documentation.less
  docs/email/guidelines/getting-started.html
  docs/email/templates/long-transactional.html
  docs/email/templates/major-announcements.html
  docs/email/templates/promotional.html
  docs/email/templates/short-transactional.html
Labels: docs

#695 Switch to new flex classes in all examples
  docs/product/components/buttons.html
  docs/product/components/inputs.html
  docs/product/components/labels.html
  docs/product/components/menus.html
  docs/product/components/modals.html
  docs/product/components/notices.html
  docs/product/components/progress-bars.html
  docs/product/components/radio.html
  docs/product/components/select.html
  docs/product/components/tags.html
  docs/product/components/textarea.html
  docs/product/components/toggle-switch.html
  docs/product/components/user-cards.html
  docs/product/guidelines/conditional-classes.html
Labels: docs

#665 Adapt tab focus to changes in modals
  docs/product/components/modals.html
  lib/ts/controllers/s-modal.ts
Labels: bug, javascript
