Repository StackExchange/Stacks, pull requests merged in 2021-03, with the labels that each got.

#596 Bump TypeScript to 4.2.2
  dist/js/stacks.js
  dist/js/stacks.min.js
  package-lock.json
  package.json
Labels: dependencies

#595 Upgrade to Less 4.0
  lib/css/atomic/_stacks-borders.less
  lib/css/atomic/_stacks-grid.less
  lib/css/atomic/_stacks-misc.less
  lib/css/atomic/_stacks-spacing.less
  lib/css/components/_stacks-tables.less
  lib/css/components/_stacks-tags.less
  lib/css/components/_stacks-widget-static.less
  lib/css/exports/_stacks-constants-helpers.less
  lib/css/exports/_stacks-constants-type.less
  package-lock.json
  package.json
Labels: dependencies

#603 Don't double grey-out `.s-description`
  lib/css/components/_stacks-inputs.less
Labels: bug

#604 Stacked cards
  docs/product/components/cards.html
Labels: enhancement

#608 Various docs improvements
  Gruntfile.js
  docs/_data/site.json
  docs/_includes/head.html
  docs/_includes/scripts.html
  docs/product/resources/icons.html
  docs/product/resources/spots.html
  package-lock.json
  package.json
Labels: lib update

#610 Add segmented progress bar
  docs/product/components/progress-bars.html
  lib/css/components/_stacks-progress-bars.less
Labels: enhancement

#605 Menu component
  docs/_data/links.json
  docs/_data/menu.json
  docs/_data/site-navigation.json
  docs/assets/js/navigation.js
  docs/assets/js/search.js
  docs/product/components/links.html
  docs/product/components/menus.html
  lib/css/components/_stacks-links.less
  lib/css/components/_stacks-menu.less
  lib/css/components/_stacks-navigation.less
  lib/css/exports/_stacks-constants-helpers.less
  lib/css/stacks-static.less
Labels: component

#613 Add an "Edit on GitHub" button
  docs/_includes/layouts/page-nomenu.html
  docs/_includes/layouts/page.html
Labels: docs

#621 Add `s-progress__segmented` to the list classes in docs
  docs/product/components/progress-bars.html
Labels: docs
