Repository StackExchange/Stacks, pull requests merged in 2021-08, with the labels that each got.

#729 Remove `grid` and `grid--cell`
  docs/_data/flex.json
  docs/brand/colors.html
  docs/brand/logo.html
  docs/email/guidelines/getting-started.html
  docs/email/templates/major-announcements.html
  docs/product/base/backgrounds.html
  docs/product/base/box-shadow.html
  docs/product/base/flex.html
  docs/product/base/overflow.html
  docs/product/components/popovers.html
  docs/product/components/sidebar-widgets.html
  docs/product/resources/icons.html
  docs/product/resources/spots.html
  lib/css/atomic/_stacks-flex.less
Labels: chore

#690 Add Uploader component
  docs/_data/site-navigation.json
  docs/_data/uploader-component.json
  docs/product/components/uploader.html
  lib/css/components/_stacks-uploader.less
  lib/css/stacks-static.less
  lib/ts/controllers/s-uploader.ts
Labels: component

#740 Explain the static width classes
  docs/product/base/width-height.html
Labels: docs

#743 Additional staff / moderator badge tweaks
  lib/css/components/_stacks-badges.less
Labels: enhancement

#748 Staff badge contrast tweaks
  lib/css/components/_stacks-badges.less
Labels: enhancement
