Repository StackExchange/Stacks, pull requests merged in 2021-11, with the labels that each got.

#788 Various buttons and links improvements
  docs/_data/links.json
  docs/product/components/buttons.html
  docs/product/components/links.html
  lib/css/components/_stacks-buttons.less
  lib/css/components/_stacks-links.less
Labels: bug, polish

#786 Add Stacks color stops indicators to /brand/data-visualization
  docs/brand/data-visualization.html
Labels: enhancement, brand, documentation

#754 Topbar component
  docs/.eleventy.js
  docs/_data/site-navigation.json
  docs/_data/topbar.json
  docs/_includes/header.html
  docs/assets/js/feature.topbar.js
  docs/assets/js/hamburger.js
  docs/assets/js/navigation.js
  docs/assets/js/search.js
  docs/assets/less/stacks-documentation.less
  docs/product/components/partials/_topbar.html
  docs/product/components/topbar.html
  lib/css/components/_stacks-badges.less
  lib/css/components/_stacks-navigation.less
  lib/css/components/_stacks-topbar.less
  lib/css/exports/_stacks-constants-colors.less
  lib/css/exports/_stacks-constants-helpers.less
  lib/css/stacks-dynamic.less
  lib/css/stacks-static.less
Labels: do-not-merge, work-in-progress, component

#795 Bump Stylelint to 14
  .stylelintrc
  lib/css/atomic/_stacks-flex.less
  lib/css/components/_stacks-badges.less
  lib/css/components/_stacks-progress-bars.less
  package-lock.json
  package.json
Labels: dependencies

#793 Final flex cleanup
  docs/brand/data-visualization.html
  docs/product/components/cards.html
  lib/css/atomic/_stacks-flex.less
Labels: deprecation

#796 Move lists reset from Stack Overflow into Stacks
  lib/css/atomic/_stacks-typography.less
Labels: enhancement
