Repository StackExchange/Stacks, pull requests merged in 2021-04, with the labels that each got.

#614 Change modal <a href="#"> to <button>
  docs/assets/js/feature.modals.js
  docs/product/components/modals.html
Labels: docs

#627 Remove `.s-btn__lg` and `.s-btn__xl`
  docs/_data/buttons.json
  lib/css/components/_stacks-buttons.less
Labels: deprecation

#617 Explore adding 1px margin and padding classes
  docs/_data/spacing.json
  docs/product/base/spacing.html
  lib/css/atomic/_stacks-spacing.less
Labels: enhancement

#631 Explicitly load the stacks-internals configuration
  lib/css/components/_stacks-tags.less
Labels: bug

#615 Popover utils and auto-show
  dist/js/stacks.js
  dist/js/stacks.min.js
  docs/assets/js/feature.popovers.js
  docs/product/components/popovers.html
  lib/ts/controllers/s-popover.ts
Labels: enhancement
