Repository StackExchange/Stacks, pull requests merged in 2021-05, with the labels that each got.

#639 Add an activity indicator
  docs/_data/activity-indicator.json
  docs/_data/site-navigation.json
  docs/product/components/activity-indicator.html
  lib/css/components/_stacks-activity-indicator.less
  lib/css/stacks-static.less
Labels: component

#547 Posts summary component
  docs/_data/post-summary.json
  docs/_data/site-navigation.json
  docs/assets/img/placeholder.svg
  docs/assets/js/navigation.js
  docs/product/components/post-summary.html
  lib/css/components/_stacks-post-summary.less
  lib/css/components/_stacks-user-cards.less
  lib/css/stacks-static.less
Labels: component

#640 Add support for multiple expandables from a single controller
  docs/product/components/expandable.html
  lib/ts/controllers/s-expandable-control.ts
Labels: component, javascript

#650 s-expandable: Prevent click after keydown on Firefox
  lib/ts/controllers/s-expandable-control.ts
Labels: bug, javascript

#616 Popover hide-on-outside-click support
  docs/product/components/popovers.html
  lib/ts/controllers/s-popover.ts
Labels: enhancement
