Repository StackExchange/Stacks, pull requests merged in 2022-07, with the labels that each got.

#999 fix(a11y): apply focus style to button unset, link
  lib/css/components/buttons.less
Labels: accessibility

#1000 fix(a11y): fix topbar forced dark mode navigation item focus style
  lib/css/components/topbar.less
Labels: accessibility

#1024 fix(button): contrast, focus state fixes
  lib/css/components/buttons.less
Labels: accessibility

#1025 modify ignored post summary selectors to be more specific
  lib/css/components/post-summary.less
Labels: bug

#1031 docs(height): fix hmx-screen typos
  docs/_data/atomics.json
  lib/css/atomic/width-height.less
Labels: docs

#1026 chore(post-summary): remove legacy variant
  docs/product/components/post-summary.html
  lib/css/components/post-summary.less
Labels: chore, breaking changes

#1042 docs(content): add section, link to Naming guidelines
  docs/content/guidelines/grammar-and-mechanics.html
Labels: brand, documentation
