Repository StackExchange/Stacks, pull requests merged in 2022-05, with the labels that each got.

#926 Remove grunt-concurrent dependency
  package-lock.json
  package.json
Labels: dependencies

#932 add accessibility attributes to s-popover
  lib/ts/controllers/s-popover.ts
Labels: javascript, accessibility

#939 fix: add back x/y margin negative classes
  lib/css/atomic/spacing.less
Labels: bug

#946 Merge develop (v1.1.0) into production
  docs/_includes/header.html
  docs/_includes/layouts/page.html
  docs/_includes/topbar.html
  docs/plugins/highlight.js
  docs/product/components/avatars.html
  docs/product/components/select.html
  docs/product/components/sidebar-widgets.html
  docs/product/components/spinner.html
  docs/product/components/textarea.html
  docs/product/components/topbar.html
  docs/product/components/uploader.html
  docs/product/components/user-cards.html
  docs/product/guidelines/theming.html
  docs/product/guidelines/using-stacks.html
  lib/css/atomic/spacing.less
  lib/css/components/activity-indicator.less
  lib/ts/controllers/s-popover.ts
  package-lock.json
  package.json
Labels: chore
