Repository StackExchange/Stacks, pull requests merged in 2022-11, with the labels that each got.

#1160 docs(adr): add a template for adrs
  adrs/0000-template.md
  adrs/README.md
Labels: adr

#1171 fix(docs): use compatible elements for current notice role
  docs/product/components/notices.html
Labels: docs, accessibility

#1173 Add distinct code of conduct file and Netlify badge
  CODE_OF_CONDUCT.md
  docs/_includes/layouts/page.html
Labels: chore, documentation

#1087 fix(topbar): add required `nav` element around navigational `<ol>`s
  docs/_data/topbar.json
  docs/_includes/topbar.html
  docs/product/components/topbar.html
  lib/css/components/topbar.less
Labels: accessibility

#1135 refactor(button-group): add radio layout
  docs/_data/button-groups.json
  docs/product/components/button-groups.html
  lib/css/components/button-groups.less
  lib/css/components/buttons.less
Labels: enhancement, work-in-progress, component, deprecation

#1077 Opinionated checkbox and radio layout
  docs/_data/site-navigation.json
  docs/assets/less/stacks-documentation.less
  docs/product/components/checkbox.html
  docs/product/components/radio.html
  lib/css/components/inputs.less
Labels: do-not-merge, docs, enhancement, component

#1179 refactor(notice): match style template
  lib/css/components/notices.less
Labels: chore

#1153 refactor(progress): use pseudo-private custom properties
  docs/product/components/progress-bars.html
  lib/css/components/progress-bars.less
Labels: deprecation

#1172 docs: add ADR for pseudo-private-custom-properties
  adrs/0000-template.md
  adrs/0001-pseudo-private-custom-properties.md
  lib/css/components/_styles-template.less
Labels: adr

#1192 Add a link to more information on flex
  docs/product/base/flex.html
Labels: documentation
