Repository StackExchange/Stacks, pull requests merged in 2022-03, with the labels that each got.

#865 Refine the spacing under Post Summary titles
  lib/css/components/_stacks-post-summary.less
Labels: polish

#867 Add `*-screen` atomic width/height classes
  docs/_data/atomics.json
  docs/product/base/width-height.html
  lib/css/atomic/_stacks-width-height.less
Labels: docs, enhancement

#871 Normalize post summary title icon placement
  docs/product/components/post-summary.html
  lib/css/components/_stacks-post-summary.less
  package-lock.json
  package.json
Labels: polish

#707 Migrate to Webpack
  Gruntfile.js
  docs/.eleventy.js
  docs/_includes/head.html
  docs/_includes/scripts.html
  docs/assets/js/controllers.d.ts
  docs/assets/js/controllers/docs-resizer.ts
  docs/assets/js/controllers/stimulus.d.ts
  docs/assets/js/entry.banners.js
  docs/assets/js/entry.brand.colors.js
  docs/assets/js/entry.colors.js
  docs/assets/js/entry.icons.js
  docs/assets/js/entry.modals.js
  docs/assets/js/entry.notices.js
  docs/assets/js/entry.popovers.js
  docs/assets/js/entry.prose.js
  docs/assets/js/entry.stacks-editor.js
  docs/assets/js/entry.topbar.js
  docs/assets/js/global.feedback.js
  docs/assets/js/global.hamburger.js
  docs/assets/js/global.navigation.js
  docs/assets/js/global.search.js
  docs/assets/js/global.theming.js
  docs/assets/js/index.ts
  docs/assets/js/svg-search.js
  docs/assets/js/tsconfig.json
  docs/assets/less/stacks-documentation.less
  docs/brand/colors.html
  docs/product/base/colors.html
  docs/product/components/banners.html
  docs/product/components/editor.html
  docs/product/components/modals.html
  docs/product/components/notices.html
  docs/product/components/popovers.html
  docs/product/components/prose.html
  docs/product/components/topbar.html
  docs/product/resources/icons.html
  docs/product/resources/spots.html
  docs/webpack.config.js
  lib/ts/controllers/index.ts
  lib/ts/controllers/s-expandable-control.ts
  lib/ts/controllers/s-modal.ts
  lib/ts/controllers/s-navigation-tablist.ts
  lib/ts/controllers/s-popover.ts
  lib/ts/controllers/s-table.ts
  lib/ts/controllers/s-tooltip.ts
  lib/ts/controllers/s-uploader.ts
  lib/ts/finalize.ts
  lib/ts/index.ts
  lib/ts/stacks.ts
  lib/ts/stimulus.d.ts
  lib/tsconfig.json
  netlify.toml
  package-lock.json
  package.json
  webpack.config.js
Labels: setup

#882 Remove dynamic config
  lib/css/base/_stacks-body.less
  lib/css/base/_stacks-configuration-dynamic.less
  lib/css/base/_stacks-internals.less
  lib/css/components/_stacks-banners.less
  lib/css/components/_stacks-buttons.less
  lib/css/components/_stacks-tags.less
  lib/css/exports/_stacks-constants-colors.less
  lib/css/stacks-dynamic.less
Labels: deprecation, chore, breaking changes

#890 Add linters
  .editorconfig
  .eslintignore
  .eslintrc.js
  .prettierignore
  .prettierrc
  .vscode/extensions.json
  package-lock.json
  package.json
Labels: polish

#898 Migrate s-topbar--ctas to s-topbar--item__unset
  docs/_data/topbar.json
  docs/_includes/topbar.html
  docs/product/components/topbar.html
  lib/css/components/_stacks-topbar.less
Labels: polish

#893 Replace Less border-radius (`@br-*`) variables with CSS variables
  docs/assets/less/stacks-documentation.less
  lib/css/atomic/_stacks-borders.less
  lib/css/components/_stacks-avatars.less
  lib/css/components/_stacks-badges.less
  lib/css/components/_stacks-buttons.less
  lib/css/components/_stacks-cards.less
  lib/css/components/_stacks-code-blocks.less
  lib/css/components/_stacks-inputs.less
  lib/css/components/_stacks-link-previews.less
  lib/css/components/_stacks-modals.less
  lib/css/components/_stacks-notices.less
  lib/css/components/_stacks-pagination.less
  lib/css/components/_stacks-popovers.less
  lib/css/components/_stacks-post-summary.less
  lib/css/components/_stacks-progress-bars.less
  lib/css/components/_stacks-prose.less
  lib/css/components/_stacks-spinner.less
  lib/css/components/_stacks-tags.less
  lib/css/components/_stacks-uploader.less
  lib/css/components/_stacks-user-cards.less
  lib/css/components/_stacks-widget-static.less
Labels: chore, breaking changes

#894 Replace Less box-shadow (`@bs-*`) variables with CSS variables
  lib/css/exports/_stacks-constants-colors.less
Labels: chore, breaking changes

#895 Replace Less z-index (`@zi-*`) variables with CSS variables
  docs/assets/less/stacks-documentation.less
  lib/css/atomic/_stacks-misc.less
  lib/css/components/_stacks-banners.less
  lib/css/components/_stacks-button-groups.less
  lib/css/components/_stacks-buttons.less
  lib/css/components/_stacks-inputs.less
  lib/css/components/_stacks-links.less
  lib/css/components/_stacks-modals.less
  lib/css/components/_stacks-navigation.less
  lib/css/components/_stacks-notices.less
  lib/css/components/_stacks-popovers.less
  lib/css/components/_stacks-progress-bars.less
  lib/css/components/_stacks-topbar.less
  lib/css/components/_stacks-uploader.less
  lib/css/exports/_stacks-constants-helpers.less
Labels: chore, breaking changes

#897 Replace Less transition (`@te-*`) variables with CSS variables
  lib/css/atomic/_stacks-misc.less
  lib/css/components/_stacks-buttons.less
  lib/css/components/_stacks-modals.less
  lib/css/components/_stacks-notices.less
  lib/css/components/_stacks-topbar.less
  lib/css/exports/_stacks-constants-helpers.less
Labels: chore, breaking changes

#896 Replace Less font-family (`@ff-*`), font-size (`@fs-*`), line-height (`@lh-*`) variables with CSS variables
  docs/assets/less/stacks-documentation.less
  lib/css/atomic/_stacks-typography.less
  lib/css/base/_stacks-body.less
  lib/css/components/_stacks-activity-indicator.less
  lib/css/components/_stacks-badges.less
  lib/css/components/_stacks-banners.less
  lib/css/components/_stacks-blank-states.less
  lib/css/components/_stacks-breadcrumbs.less
  lib/css/components/_stacks-buttons.less
  lib/css/components/_stacks-code-blocks.less
  lib/css/components/_stacks-inputs.less
  lib/css/components/_stacks-link-previews.less
  lib/css/components/_stacks-menu.less
  lib/css/components/_stacks-modals.less
  lib/css/components/_stacks-navigation.less
  lib/css/components/_stacks-notices.less
  lib/css/components/_stacks-page-titles.less
  lib/css/components/_stacks-pagination.less
  lib/css/components/_stacks-popovers.less
  lib/css/components/_stacks-post-summary.less
  lib/css/components/_stacks-progress-bars.less
  lib/css/components/_stacks-prose.less
  lib/css/components/_stacks-tables.less
  lib/css/components/_stacks-tags.less
  lib/css/components/_stacks-toggle-switches.less
  lib/css/components/_stacks-topbar.less
  lib/css/components/_stacks-uploader.less
  lib/css/components/_stacks-user-cards.less
  lib/css/components/_stacks-widget-static.less
  lib/css/exports/_stacks-constants-type.less
Labels: chore, breaking changes
