Repository StackExchange/Stacks, pull requests merged in 2022-04, with the labels that each got.

#903 Use CSS variables for s-step and s-full
  lib/css/atomic/_stacks-width-height.less
  lib/css/components/_stacks-banners.less
  lib/css/components/_stacks-topbar.less
  lib/css/exports/_stacks-constants-helpers.less
Labels: chore

#906 Drop `_stacks-` from filenames
  lib/css/atomic/borders.less
  lib/css/atomic/colors.less
  lib/css/atomic/flex.less
  lib/css/atomic/grid.less
  lib/css/atomic/misc.less
  lib/css/atomic/spacing.less
  lib/css/atomic/typography.less
  lib/css/atomic/width-height.less
  lib/css/base/body.less
  lib/css/base/configuration-static.less
  lib/css/base/icons.less
  lib/css/base/internals.less
  lib/css/base/reset-meyer.less
  lib/css/base/reset-normalize.less
  lib/css/base/reset.less
  lib/css/components/activity-indicator.less
  lib/css/components/avatars.less
  lib/css/components/badges.less
  lib/css/components/banners.less
  lib/css/components/blank-states.less
  lib/css/components/breadcrumbs.less
  lib/css/components/button-groups.less
  lib/css/components/buttons.less
  lib/css/components/cards.less
  lib/css/components/code-blocks.less
  lib/css/components/collapsible.less
  lib/css/components/inputs.less
  lib/css/components/link-previews.less
  lib/css/components/links.less
  lib/css/components/menu.less
  lib/css/components/modals.less
  lib/css/components/navigation.less
  lib/css/components/notices.less
  lib/css/components/page-titles.less
  lib/css/components/pagination.less
  lib/css/components/popovers.less
  lib/css/components/post-summary.less
  lib/css/components/progress-bars.less
  lib/css/components/prose.less
  lib/css/components/spinner.less
  lib/css/components/tables.less
  lib/css/components/tags.less
  lib/css/components/toggle-switches.less
  lib/css/components/topbar.less
  lib/css/components/uploader.less
  lib/css/components/user-cards.less
  lib/css/components/widget-dynamic.less
  lib/css/components/widget-static.less
  lib/css/exports/constants-colors.less
  lib/css/exports/constants-helpers.less
  lib/css/exports/constants-type.less
  lib/css/exports/exports.less
  lib/css/exports/mixins.less
  lib/css/stacks-dynamic.less
  lib/css/stacks-static.less
Labels: chore, breaking changes

#904 Remove `@su*` Less vars and references
  lib/css/atomic/flex.less
  lib/css/components/topbar.less
  lib/css/components/widget-static.less
  lib/css/exports/constants-helpers.less
Labels: deprecation, chore, breaking changes

#816 Forced theme component colors
  lib/css/components/buttons.less
  lib/css/exports/constants-colors.less
  lib/css/exports/mixins.less
Labels: bug, dark-mode, component

#915 Restore 0 margin and padding
  lib/css/atomic/spacing.less
Labels: bug
