Repository StackExchange/Stacks, pull requests merged in 2022-08, with the labels that each got.

#1009 refactor(eslint): fix controller eslint/typescript errors
  lib/ts/controllers/s-expandable-control.ts
  lib/ts/controllers/s-modal.ts
  lib/ts/controllers/s-navigation-tablist.ts
  lib/ts/controllers/s-popover.ts
  lib/ts/controllers/s-table.ts
  lib/ts/controllers/s-tooltip.ts
  lib/ts/stacks.ts
Labels: javascript, chore

#1040 Pull in classes from Stacks-Editor
  docs/_data/spinner.json
  docs/product/components/inputs.html
  docs/product/components/spinner.html
  lib/css/components/buttons.less
  lib/css/components/inputs.less
  lib/css/components/spinner.less
Labels: enhancement

#1046 refactor(label): move .s-label Less to standalone file
  lib/css/components/inputs.less
  lib/css/components/labels.less
  lib/css/stacks-static.less
Labels: component, chore

#1015 fix(breadcrumbs): meet WCAG 2 AA contrast
  lib/css/components/breadcrumbs.less
Labels: accessibility

#1048 Fix lingering accessibility issues found by Mabl
  docs/_includes/markdown-prose.md
  docs/_includes/markdown-sandbox.md
  docs/product/components/badges.html
  docs/product/components/breadcrumbs.html
  docs/product/components/menus.html
  docs/product/components/navigation.html
  docs/product/components/page-titles.html
  docs/product/components/popovers.html
  docs/product/components/prose.html
  docs/product/components/tables.html
  lib/ts/controllers/s-expandable-control.ts
Labels: docs, accessibility

#1022 refactor(components): Merge .s-banner into .s-notice; fix a11y issues
  docs/_data/banners.json
  docs/assets/js/entry.banners.js
  docs/product/components/banners.html
  docs/product/components/notices.html
  lib/css/components/banners.less
  lib/css/components/notices.less
  lib/css/stacks-dynamic.less
Labels: component, accessibility, breaking changes

#1065 fix(labels): increase contrast
  lib/css/components/labels.less
Labels: accessibility

#1066 docs(button-group): document aria-current attribute usage
  docs/product/components/button-groups.html
Labels: docs, accessibility

#1078 fix(tooltip): resolve accessibility issues
  lib/ts/controllers/s-tooltip.ts
Labels: accessibility
