Repository StackExchange/Stacks, pull requests merged in 2022-02, with the labels that each got.

#849 Additional post summary refinements
  docs/_data/post-summary.json
  docs/product/components/post-summary.html
  lib/css/components/_stacks-post-summary.less
Labels: polish

#850 Various documentation fixes
  docs/_includes/markdown-sandbox.md
  docs/email/templates/code/transactional-short.html
  docs/product/components/cards.html
  docs/product/components/post-summary.html
  netlify.toml
Labels: docs, polish

#852 Add break-word to post-summary excerpt
  lib/css/components/_stacks-post-summary.less
Labels: bug
