Repository StackExchange/Stacks, pull requests merged in 2022-01, with the labels that each got.

#807 Badge and privilege progress bar refinements
  docs/product/components/progress-bars.html
  lib/css/components/_stacks-progress-bars.less
Labels: polish

#806 Add more article states
  docs/product/components/post-summary.html
  lib/css/components/_stacks-post-summary.less
Labels: enhancement

#826 Justify user-cards to the right in post-summary
  lib/css/components/_stacks-post-summary.less
Labels: bug, component

#820 Switch to native gaps on user cards
  docs/product/components/user-cards.html
  lib/css/components/_stacks-user-cards.less
Labels: polish

#827 Darken the highlighted user cards a bit
  lib/css/components/_stacks-user-cards.less
Labels: enhancement, polish

#830 Add links to Figma components
  docs/_includes/layouts/page.html
  docs/product/base/box-shadow.html
  docs/product/base/colors.html
  docs/product/base/typography.html
  docs/product/components/avatars.html
  docs/product/components/badges.html
  docs/product/components/banners.html
  docs/product/components/breadcrumbs.html
  docs/product/components/button-groups.html
  docs/product/components/buttons.html
  docs/product/components/cards.html
  docs/product/components/checkbox.html
  docs/product/components/editor.html
  docs/product/components/inputs.html
  docs/product/components/labels.html
  docs/product/components/modals.html
  docs/product/components/navigation.html
  docs/product/components/notices.html
  docs/product/components/popovers.html
  docs/product/components/radio.html
  docs/product/components/select.html
  docs/product/components/tags.html
  docs/product/components/textarea.html
  docs/product/components/toggle-switch.html
  docs/product/resources/icons.html
  docs/product/resources/spots.html
Labels: documentation

#831 Remove flex start from post summaries
  lib/css/components/_stacks-post-summary.less
Labels: bug

#835 Add additional lengths to post summary excerpts
  docs/_data/post-summary.json
  docs/product/components/post-summary.html
  lib/css/components/_stacks-post-summary.less
Labels: enhancement

#836 Fix stateful title color specificity
  lib/css/components/_stacks-post-summary.less
Labels: enhancement

#838 Post summary stats order
  docs/product/components/post-summary.html
Labels: documentation

#842 Add focus states to multiple options toggle switch
  lib/css/components/_stacks-toggle-switches.less
Labels: accessibility
